### ISSUE TITLE
user profile: talents status

### ISSUE THREAD

**Issue by mstuder** [flux-eco/flux-eco-ehf-app-backend#7]
current:
```
{
  "talents": 20,
  "uncompletedTrainingSessions": ["anti-doping"],
  "completedTrainingSessions": [],
  "upcomingAmbassadorSessions": ["meetJohn"],
  "group": "trainee"
}
```

**Comment by mstuder** [comment]
@nikola-oblak - what you mean with talent status. may you specify that?

**Comment by nikola-oblak** [comment]
I meant the current number of talents the user has.
But I see that it is already contained in the response. Then it's all right.
